package ru.bobans.map_obj;//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.20 at 11:55:09 AM MSK 
//


import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Файл }
     * 
     */
    public Файл createФайл() {
        return new Файл();
    }

    /**
     * Create an instance of {@link Файл.Персона }
     * 
     */
    public Файл.Персона createФайлПерсона() {
        return new Файл.Персона();
    }

    /**
     * Create an instance of {@link Файл.Персона.СлужИнфо }
     * 
     */
    public Файл.Персона.СлужИнфо createФайлПерсонаСлужИнфо() {
        return new Файл.Персона.СлужИнфо();
    }

    /**
     * Create an instance of {@link Файл.Персона.Счета }
     * 
     */
    public Файл.Персона.Счета createФайлПерсонаСчета() {
        return new Файл.Персона.Счета();
    }

    /**
     * Create an instance of {@link Файл.Персона.ЦенныеБумаги }
     * 
     */
    public Файл.Персона.ЦенныеБумаги createФайлПерсонаЦенныеБумаги() {
        return new Файл.Персона.ЦенныеБумаги();
    }

    /**
     * Create an instance of {@link Файл.Персона.ПерсИнфо }
     * 
     */
    public Файл.Персона.ПерсИнфо createФайлПерсонаПерсИнфо() {
        return new Файл.Персона.ПерсИнфо();
    }

    /**
     * Create an instance of {@link Файл.Запрос }
     * 
     */
    public Файл.Запрос createФайлЗапрос() {
        return new Файл.Запрос();
    }

    /**
     * Create an instance of {@link Файл.ИнфОрг }
     * 
     */
    public Файл.ИнфОрг createФайлИнфОрг() {
        return new Файл.ИнфОрг();
    }

    /**
     * Create an instance of {@link Файл.Персона.СлужИнфо.ИДИнфо }
     * 
     */
    public Файл.Персона.СлужИнфо.ИДИнфо createФайлПерсонаСлужИнфоИДИнфо() {
        return new Файл.Персона.СлужИнфо.ИДИнфо();
    }

    /**
     * Create an instance of {@link Файл.Персона.СлужИнфо.Наименование }
     * 
     */
    public Файл.Персона.СлужИнфо.Наименование createФайлПерсонаСлужИнфоНаименование() {
        return new Файл.Персона.СлужИнфо.Наименование();
    }

    /**
     * Create an instance of {@link Файл.Персона.Счета.Счет }
     * 
     */
    public Файл.Персона.Счета.Счет createФайлПерсонаСчетаСчет() {
        return new Файл.Персона.Счета.Счет();
    }

    /**
     * Create an instance of {@link Файл.Персона.Счета.КредитОрг }
     * 
     */
    public Файл.Персона.Счета.КредитОрг createФайлПерсонаСчетаКредитОрг() {
        return new Файл.Персона.Счета.КредитОрг();
    }

    /**
     * Create an instance of {@link Файл.Персона.ЦенныеБумаги.Организация }
     * 
     */
    public Файл.Персона.ЦенныеБумаги.Организация createФайлПерсонаЦенныеБумагиОрганизация() {
        return new Файл.Персона.ЦенныеБумаги.Организация();
    }

    /**
     * Create an instance of {@link Файл.Персона.ЦенныеБумаги.Бумага }
     * 
     */
    public Файл.Персона.ЦенныеБумаги.Бумага createФайлПерсонаЦенныеБумагиБумага() {
        return new Файл.Персона.ЦенныеБумаги.Бумага();
    }

    /**
     * Create an instance of {@link Файл.Персона.ПерсИнфо.ФИОД }
     * 
     */
    public Файл.Персона.ПерсИнфо.ФИОД createФайлПерсонаПерсИнфоФИОД() {
        return new Файл.Персона.ПерсИнфо.ФИОД();
    }

    /**
     * Create an instance of {@link Файл.Персона.ПерсИнфо.Документ }
     * 
     */
    public Файл.Персона.ПерсИнфо.Документ createФайлПерсонаПерсИнфоДокумент() {
        return new Файл.Персона.ПерсИнфо.Документ();
    }

    /**
     * Create an instance of {@link Файл.Персона.ПерсИнфо.Адрес }
     * 
     */
    public Файл.Персона.ПерсИнфо.Адрес createФайлПерсонаПерсИнфоАдрес() {
        return new Файл.Персона.ПерсИнфо.Адрес();
    }

    public FileKvit createFileKvit() {
        return new FileKvit();
    }


}
